In [54]:
import numpy as np
a = np.array([0.3, 0.1, 0.6, 0.8, 0.1, 1, 0, 0, 0, 0.5])
print(a)

[0.3 0.1 0.6 0.8 0.1 1.  0.  0.  0.  0.5]


In [55]:
type(a)

numpy.ndarray

In [56]:
matriz = [[1,2,3],[4,5,6]]
b = np.array(matriz)
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [57]:
c =np.zeros((5,3)) #Crea matrices nulas(todas las dimenciones son cero)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
d = np.identity((3)) #Crea ,atriz identidad (diagonal con valor 1 y demas valores en cero) con tamaño de matriz definida en el parametro. Debe ser matriz cuadrada
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
e = np.arange(0,9,1) #Crea un array con los valores del rango 0 a 9 sin incluir el 9
print(e)

[0 1 2 3 4 5 6 7 8]


In [60]:
f = np.linspace(0,100,5) #Crea un array con los valores del rango(incluido inferior y maximo) y marca la distancia numerica entre cada uno de los elementos
print(f)

[  0.  25.  50.  75. 100.]


In [61]:
np.ndim(e) #Calcula las dimensiones de la matriz

1

In [62]:
np.shape(c) #Calcula el numero de filas y columnas de la matriz

(5, 3)

In [63]:
np.size(c) #Calcula la cantidad de elementos de una matriz

15

In [64]:
c.dtype #Valida el tipo de dato que contiene la matriz

dtype('float64')

In [65]:
b[1,2] #Sintaxis para acceder a los valores de una matriz (fila, columna)

np.int64(6)

In [66]:
b[(b > 2) & (b < 5)] #Recorre los valores de la matriz e imprime los valores que cumplen el condicional

array([3, 4])

In [67]:
matriz1 = np.array([[1,2,3],[4,5,6]])
matriz2 = np.array([[7,8,9],[10,11,12]])

In [68]:
suma = matriz1 + matriz2
print(suma)

[[ 8 10 12]
 [14 16 18]]


In [69]:
resta = matriz1 - matriz2
print(resta)

[[-6 -6 -6]
 [-6 -6 -6]]


In [70]:
multiplicacion = matriz1 * matriz2
print(multiplicacion)

[[ 7 16 27]
 [40 55 72]]


In [71]:
dividir = matriz1 / matriz2
print(dividir)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [72]:
dividir2 = matriz1 % matriz2
print(dividir2)

[[1 2 3]
 [4 5 6]]


In [73]:
exponente = matriz1 ** matriz2
print(exponente)

[[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [74]:
#Producto Escalar
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
producto = vector1.dot(vector2)
print(producto)

32


In [75]:
#Modulo de un Vector
mvector = np.linalg.norm(vector1)
print(mvector)

3.7416573867739413


In [76]:
matriz3 = np.array([[1,2],[3,4],[5,6]])
pmatricial = matriz1.dot(matriz3)
print(pmatricial)

[[22 28]
 [49 64]]


In [77]:
matriz1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
trazamatriz = np.array([[2,4,],[8,10]])
print(trazamatriz)
trazamatriz.trace()

[[ 2  4]
 [ 8 10]]


np.int64(12)

In [79]:
print(round(np.linalg.det(trazamatriz)))

-12


In [80]:
np.linalg.inv(trazamatriz)

array([[-0.83333333,  0.33333333],
       [ 0.66666667, -0.16666667]])

In [81]:
np.linalg.eigvals(trazamatriz)

array([-0.92820323, 12.92820323])